USE TutoratoSmartTest;

DELETE FROM ACTIVITY_TUTOR;
DELETE FROM APPOINTMENT;
DELETE FROM CONTAINED_IN;
DELETE FROM MANAGES;
DELETE FROM REQUEST;
DELETE FROM STUDENT;
DELETE FROM TUTOR;
DELETE FROM REGISTER;
DELETE FROM VALIDATES;
DELETE FROM TS_USER;