package project.SystemTesting;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ManageRequestSuccessSystemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void manageRequest() {
	  
	driver.get("http://localhost:8080/TutoratoSmart/");
	driver.manage().window().setSize(new Dimension(867, 783));
	driver.findElement(By.linkText("Accedi")).click();
	driver.findElement(By.id("email")).click();
	driver.findElement(By.id("email")).sendKeys("m.pisciotta@studenti.unicampania.it");
	driver.findElement(By.id("password")).click();
	driver.findElement(By.id("password")).sendKeys("M12345678");
	driver.findElement(By.id("login")).click();
	    
    driver.get("http://localhost:8080/TutoratoSmart/");
    driver.manage().window().setSize(new Dimension(1234, 785));
    driver.findElement(By.linkText("Gestione Sportello")).click();
    {
      WebElement element = driver.findElement(By.linkText("Nuove Prenotazioni"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }

    driver.findElement(By.linkText("Nuove Prenotazioni")).click();
    
    driver.get("http://localhost:8080/TutoratoSmart/ShowRequest?flag=4");
    driver.findElement(By.linkText("Mostra")).click();
    
    driver.get("http://localhost:8080/TutoratoSmart/ShowRequest?id=7&flag=3");
    driver.findElement(By.id("acceptRequest")).click();
    
    driver.findElement(By.id("requestDuration")).click();
    driver.findElement(By.id("requestDuration")).sendKeys("60");
    driver.findElement(By.cssSelector(".row:nth-child(1) .btn-success")).click();
  }
}
