package project.SystemTesting;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class ModifyRequestErrorSystemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modifyRequestErrorSystem() {
	  
	driver.get("http://localhost:8080/TutoratoSmart/");
	driver.manage().window().setSize(new Dimension(867, 783));
	driver.findElement(By.linkText("Accedi")).click();
	driver.findElement(By.id("email")).click();
	driver.findElement(By.id("email")).sendKeys("e.merola@studenti.unicampania.it");
	driver.findElement(By.id("password")).click();
	driver.findElement(By.id("password")).sendKeys("M12345678");
	driver.findElement(By.id("login")).click();    
	
	
    driver.get("http://localhost:8080/TutoratoSmart/home.jsp");
    driver.manage().window().setSize(new Dimension(975, 869));
    driver.findElement(By.linkText("Storico Prenotazioni")).click();
    
    driver.get("http://localhost:8080/TutoratoSmart/ShowRequest?flag=1");
    driver.findElement(By.linkText("Mostra")).click();
    
    
    driver.get("http://localhost:8080/TutoratoSmart/ShowRequest?Id=6&flag=2");  //MODIFICARE
    driver.findElement(By.id("modifyRequest")).click();
    
    driver.get("http://localhost:8080/TutoratoSmart/student/requestModify.jsp");
    
    driver.findElement(By.id("requestDateM")).click();
    driver.findElement(By.id("requestDateM")).sendKeys("2020-02-26");
    driver.findElement(By.id("requestTimeM")).click();
    driver.findElement(By.id("requestTimeM")).sendKeys("12:00");
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("Ppppppppppppppppppppppppppppppppppppppppppppppp\\r\\n\" + \n" + 
    		"				\"ppppppppppppppppppppppppppppppppppppppppppppppp\\r\\n\" + \n" + 
    		"				\"ppppppppppppppppppppppppppppppppppppppppppppppp\\r\\n\" + \n" + 
    		"				\"ppppppppppppppppppppppppppppppppppppppppppppppp\\r\\n\" + \n" + 
    		"				\"ppppppppppppppppppppppppppppppppppppppppppppppp\\r\\n\" + \n" + 
    		"				\"ppppppppppppppppppppppppppppppppppppppppppppppp\\r\\n\" + \n" + 
    		"				\"\"");
    driver.findElement(By.id("modifyRequest")).click();
  }
}
